spring.application.name=3QSpace

server.address=0.0.0.0
server.port=9999

spring.datasource.url=jdbc:mysql://localhost:3306/3qspace?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



